Repository brstu/TMAU-2023, pull requests merged in 2023-12, with the labels that each got.

#249 [task_04] Add solution
  readme.md
  trunk/as0006106/task_04/doc/readme.md
  trunk/as0006106/task_04/images/access_rights.png
  trunk/as0006106/task_04/images/create_directory.png
  trunk/as0006106/task_04/images/winscp.png
  trunk/as0006106/task_04/images/Снимок экрана (129).png
Labels: bug

#260 [task_05] Add problem solution
  readme.md
  trunk/as0006104/task_05/doc/readme.md
Labels: good first PR

#126 [task_02] Add solution
  readme.md
  trunk/as0006108/task_02/doc/Linear_Lab2.png
  trunk/as0006108/task_02/doc/Nonlinear_Lab2.png
  trunk/as0006108/task_02/doc/doxygen.md
  trunk/as0006108/task_02/doc/readme.md
  trunk/as0006108/task_02/doc/results.txt
  trunk/as0006108/task_02/src/CMakeLists.txt
  trunk/as0006108/task_02/src/Lab2.cpp
Labels: question

#262 [task_05] Add solution
  readme.md
  trunk/as0006114/task_05/doc/readme.md
Labels: question
