Repository brstu/TMAU-2023, pull requests merged in 2023-10, with the labels that each got.

#16 [doc] Add AC-61 group list
  readme.md
Labels: documentation

#19 [cmake] Add global CMake config
  .gitignore
  CMakeLists.txt
  CppProperties.json
  trunk/as0006112/task_01/src/CMakeLists.txt
Labels: title needs [task]

#18 [cpp] Fix code smells
  trunk/as0006104/task_01/src/main.cpp
  trunk/as0006112/task_01/src/main.cpp
Labels: title needs [task]

#7 [task_01] Add problem solution
  readme.md
  trunk/as0006215/task_01/doc/report.md
  trunk/as0006215/task_01/src/CMakeLists.txt
  trunk/as0006215/task_01/src/main.cpp
Labels: bug

#12 [task_01] Add solution
  readme.md
  trunk/as0006115/task_01/doc/REPORT.md
  trunk/as0006115/task_01/src/.gitignore
  trunk/as0006115/task_01/src/CMakeLists.txt
  trunk/as0006115/task_01/src/lib/model.cpp
  trunk/as0006115/task_01/src/lib/model.hpp
  trunk/as0006115/task_01/src/main.cpp
Labels: question

#8 [task_01] Pull request
  readme.md
  trunk/as0006114/task_01/doc/report.md
  trunk/as0006114/task_01/src/CMakeLists.txt
  trunk/as0006114/task_01/src/main.cpp
Labels: bug

#27 [task_01] Marina Dubnovitskaya
  trunk/as0006105/task_01/doc/readme.md
  trunk/as0006105/task_01/src/CMakeLists.txt
  trunk/as0006105/task_01/src/lab_1_github.cpp
Labels: question

#22 [task_01] Add solution
  trunk/as0006111/task_01/doc/readme.md
  trunk/as0006111/task_01/src/CMakeLists.txt
  trunk/as0006111/task_01/src/timau1.cpp
Labels: question

#9 [task_01] Muhacheva
  readme.md
  trunk/as0006217/task_01/doc/report_lab1.md
  trunk/as0006217/task_01/src/CMakeLists.txt
  trunk/as0006217/task_01/src/task1.cpp
Labels: bug

#14 [task_01] Solution
  readme.md
  trunk/as0006110/task_01/doc/readme.md
  trunk/as0006110/task_01/src/CMakeLists.txt
  trunk/as0006110/task_01/src/main.cpp
Labels: bug

#13 [task_01] Fork
  readme.md
  trunk/as0006118/task_01/doc/readme.md
  trunk/as0006118/task_01/src/CMakeLists.txt
  trunk/as0006118/task_01/src/main.cpp
Labels: question

#28 [task_01] Add solution
  readme.md
  trunk/as0006103/task_01/doc/readme.md
  trunk/as0006103/task_01/src/CMakeLists.txt
  trunk/as0006103/task_01/src/TMAU1.cpp
Labels: question
